@startuml
class MatchResult {
- int localGoalCounter
- int visitantGoalCounter
~ <<Create>> MatchResult()
+ int getLocalGoalCounter()
+ void setLocalGoalCounter(int)
+ int getVisitantGoalCounter()
+ void setVisitantGoalCounter(int)
+ void incrementLocalCounter()
+ void incrementVisitantCounter()
+ String generateMarker()
}
class Match {
- String location
- Date date
- Team localTeam
- Team visitantTeam
- MatchResult result
~ <<Create>> Match()
~ <<Create>> Match(String,Date)
~ <<Create>> Match(String,Date,Team,Team)
+ void makeGoal(Team,Player)
+ String generateMarker()
+ void setLocation(String)
+ String getLocation()
+ void setDate(Date)
+ Date getdate()
+ void setLocalTeam(Team)
+ void setVisitantTeam(Team)
+ Team getLocalTeam()
+ Team getVisitantTeam()
}
class Team {
- String name
- ArrayList<Player> players
~ <<Create>> Team(String)
+ void setName(String)
+ String getName()
+ void addPlayer(Player)
+ void setPlayers(ArrayList<Player>)
+ ArrayList<Player> getPlayers()
}
class Player {
- String name
- String position
- int goalCounter
- int matchCounter
- Team team
~ <<Create>> Player(String)
~ <<Create>> Player(String,String)
+ void setName(String)
+ String getName()
+ void setPosition(String)
+ String getPosition()
+ int getGoalCounter()
+ void setGoalCounter(int)
+ void setMatchCounter(int)
+ void incrementGoalCounter()
+ int getMatchCounter()
+ void incrementMatchCounter()
+ Team getTeam()
+ void setTeam(Team)
}
class Main {
+ {static} void main(String[])
}
class Season {
- ArrayList<Match> matchs
- String name
- Date startDate
- Date endDate
~ <<Create>> Season(String,Date,Date)
+ ArrayList<Match> getMatchesByDate(Date)
+ ArrayList<Match> addMatch(Match)
+ void setName(String)
+ String getName()
+ void setStartDate(Date)
+ void setEndDate(Date)
+ Date getStartDate()
+ Date getEndDate()
+ ArrayList<Match> getMatchs()
+ void setMatchs(ArrayList<Match>)
}
@enduml